/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    Carousel: typeof import('./src/components/carousel/Carousel.vue')['default']
    Popover: typeof import('./src/components/popover/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tutorial: typeof import('./src/components/tutorial/Tutorial.vue')['default']
  }
}
