/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ADrawer: typeof import('ant-design-vue/es')['Drawer']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    APopover: typeof import('ant-design-vue/es')['Popover']
    ARangePicker: typeof import('ant-design-vue/es')['RangePicker']
    ARow: typeof import('ant-design-vue/es')['Row']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    Button: typeof import('./src/components/button/Button.vue')['default']
    Carousel: typeof import('./src/components/carousel/Carousel.vue')['default']
    ClickEditInput: typeof import('./src/components/input/ClickEditInput.vue')['default']
    copy: typeof import('./src/components/tutorial/Tutorial copy.vue')['default']
    CustomVideo: typeof import('./src/components/video/CustomVideo.vue')['default']
    IconButton: typeof import('./src/components/button/IconButton.vue')['default']
    InteractiveTutorial: typeof import('./src/components/tutorial/InteractiveTutorial.vue')['default']
    Popover: typeof import('./src/components/popover/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/svg/SvgIcon.vue')['default']
    Tooltip: typeof import('./src/components/tips/Tooltip.vue')['default']
    Tutorial: typeof import('./src/components/tutorial/Tutorial.vue')['default']
    Tutorial2: typeof import('./src/components/tutorial/Tutorial2.vue')['default']
    UploadDragger: typeof import('./src/components/upload/UploadDragger.vue')['default']
  }
}
